# Vectors, Matrices and Multi-Dim array

In [16]:
import numpy as np

data = np.array([[1,2],[3,4],[5,6]], dtype="int32")
data.shape


(3, 2)

## Order of array data in Memory

Many common operations on arrays, such as the transpose can be implemented by simply changing the `strides` attribute,   
which can eliminate the need for moving data around in the memory. Operations that only require changing the strides atribute  
result in new `ndarray` objects that refer to the same data as original array. Such arrays are called `views`  
*for efficiency Numpy strives to create views rather than copies of arrays when applying operation on arrays*

In [29]:
data_uno = np.array([[1,2,3],[3,4,5]], dtype="int32", order="F") # Fortran
data_uno = np.array([[1,2,3],[3,4,5]], dtype="int32", order="C") # C
data_uno.strides

(12, 4)

### Take care when copying array data

In [33]:
import copy
# data_two = copy.deepcopy(data_uno[:,0])
data_two = data_uno[:,0]
data_two[:] = 0
np.shares_memory(data_two, data_uno)

True

In [28]:
data_uno

array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)

## Arrays filled with Constant Values & arrays filled with Incremental Sequences

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones(4)

array([1., 1., 1., 1.])

In [5]:
np.ones(4, dtype=np.int32)

array([1, 1, 1, 1], dtype=int32)

In [6]:
x1 = 5.4 * np.ones((2,3))
x1

array([[5.4, 5.4, 5.4],
       [5.4, 5.4, 5.4]])

In [7]:
x2 = np.full((3,2,4), 5.4)
x2

array([[[5.4, 5.4, 5.4, 5.4],
        [5.4, 5.4, 5.4, 5.4]],

       [[5.4, 5.4, 5.4, 5.4],
        [5.4, 5.4, 5.4, 5.4]],

       [[5.4, 5.4, 5.4, 5.4],
        [5.4, 5.4, 5.4, 5.4]]])

In [8]:
x1 = np.empty(5)
x1.fill(3.0)
x1

array([3., 3., 3., 3., 3.])

In [9]:
x2 = np.full(5, 3.0)
x2

array([3., 3., 3., 3., 3.])

In [10]:
np.arange(0.0, 10, 1) # could use `endpoint`

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [11]:
np.linspace(0, 10, 11, endpoint="False") #  endpoint="False"

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
np.logspace(0, 2, 5) # 5 data points between 10**0=1 to 10**2=100

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [13]:
# To define a new function which operates on Numpy arrays
# bad
def heavside(x):
    return 1 if x > 0 else 0

# This function doesn't work on 
x = np.linspace(-5, 5, 11)
# heavside(x)

# Rather use : 1. np.vectorize; which cost in time as it calls the function at each itreration
# 2. Use Boolean-valued arrays; better
# 1.
heavside = np.vectorize(heavside)
heavside(x)
# 2. 
def heavside(x):
    return 1.0*(x > 0)

In [15]:
heavside(x)

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])